-- Supabase Schema for EchoFilter

-- 1. Table for video analysis cache
CREATE TABLE IF NOT EXISTS video_analyses (
    video_id TEXT NOT NULL,
    search_query TEXT NOT NULL,
    info_density_score DOUBLE PRECISION NOT NULL,
    filler_ratio DOUBLE PRECISION NOT NULL,
    confidence_score DOUBLE PRECISION NOT NULL,
    key_timestamps JSONB NOT NULL DEFAULT '[]'::jsonb,
    verdict TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (video_id, search_query)
);

-- Index for querying by video_id
CREATE INDEX IF NOT EXISTS idx_video_analyses_video_id ON video_analyses(video_id);

-- 2. Table for community crowdsourced tags
CREATE TABLE IF NOT EXISTS community_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id TEXT NOT NULL,
    tag TEXT NOT NULL,
    user_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (video_id, user_id, tag)
);

-- Index for searching tags by video_id
CREATE INDEX IF NOT EXISTS idx_community_tags_video_id ON community_tags(video_id);
