'use client';

import React, { useState, useEffect } from 'react';

interface TopUser {
  userId: string;
  callsCount: number;
  creditsUsed: number;
}

interface DailyStat {
  date: string;
  callsCount: number;
  creditsUsed: number;
}

interface DashboardStats {
  tableExists: boolean;
  totalUsers: number;
  totalCalls: number;
  totalCreditsUsed: number;
  groqKeyConfigured: boolean;
  groqKeyStatus: string;
  topUsers: TopUser[];
  dailyStats: DailyStat[];
}

export default function AdminDashboard() {
  const [adminSecret, setAdminSecret] = useState<string>('');
  const [isAuthenticated, setIsAuthenticated] = useState<boolean>(false);
  const [secretInput, setSecretInput] = useState<string>('');
  const [loginError, setLoginError] = useState<string | null>(null);

  const [stats, setStats] = useState<DashboardStats | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [statsError, setStatsError] = useState<string | null>(null);

  const [groqKeyInput, setGroqKeyInput] = useState<string>('');
  const [configLoading, setConfigLoading] = useState<boolean>(false);
  const [configSuccess, setConfigSuccess] = useState<string | null>(null);
  const [configError, setConfigError] = useState<string | null>(null);
  const [showGroqKey, setShowGroqKey] = useState<boolean>(false);

  // Sync token from sessionStorage on mount
  useEffect(() => {
    const savedSecret = sessionStorage.getItem('echofilter_admin_secret');
    if (savedSecret) {
      setAdminSecret(savedSecret);
      setSecretInput(savedSecret);
      setIsAuthenticated(true);
    }
  }, []);

  // Fetch stats when authenticated
  useEffect(() => {
    if (isAuthenticated && adminSecret) {
      fetchStats();
    }
  }, [isAuthenticated, adminSecret]);

  const fetchStats = async () => {
    setLoading(true);
    setStatsError(null);
    try {
      const res = await fetch('/api/admin/stats', {
        headers: {
          'x-admin-secret': adminSecret,
        },
      });

      if (!res.ok) {
        if (res.status === 401) {
          sessionStorage.removeItem('echofilter_admin_secret');
          setIsAuthenticated(false);
          throw new Error('Invalid secret key. Please log in again.');
        }
        const errData = await res.json();
        throw new Error(errData.error || 'Failed to fetch telemetry stats.');
      }

      const data = await res.json();
      setStats(data);
    } catch (err: any) {
      setStatsError(err.message || 'An error occurred.');
    } finally {
      setLoading(false);
    }
  };

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    if (!secretInput.trim()) {
      setLoginError('Secret key cannot be empty.');
      return;
    }
    setLoginError(null);
    setAdminSecret(secretInput);
    setIsAuthenticated(true);
    sessionStorage.setItem('echofilter_admin_secret', secretInput);
  };

  const handleLogout = () => {
    sessionStorage.removeItem('echofilter_admin_secret');
    setIsAuthenticated(false);
    setAdminSecret('');
    setSecretInput('');
    setStats(null);
  };

  const handleUpdateConfig = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!groqKeyInput.trim()) {
      setConfigError('API Key cannot be empty.');
      return;
    }

    setConfigLoading(true);
    setConfigSuccess(null);
    setConfigError(null);

    try {
      const res = await fetch('/api/admin/config', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-admin-secret': adminSecret,
        },
        body: JSON.stringify({ groqApiKey: groqKeyInput }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'Failed to update Groq API key.');
      }

      setConfigSuccess('Groq API Key updated successfully!');
      setGroqKeyInput('');
      fetchStats(); // Refresh status badge
    } catch (err: any) {
      setConfigError(err.message || 'An error occurred.');
    } finally {
      setConfigLoading(false);
    }
  };

  const [copying, setCopying] = useState<boolean>(false);
  const sqlSchemaText = `CREATE TABLE IF NOT EXISTS usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    video_id TEXT NOT NULL,
    search_query TEXT NOT NULL,
    tokens_used INT NOT NULL DEFAULT 0,
    credits_consumed DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    using_custom_key BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_usage_logs_user_id ON usage_logs(user_id);`;

  const copySqlToClipboard = () => {
    navigator.clipboard.writeText(sqlSchemaText);
    setCopying(true);
    setTimeout(() => setCopying(false), 2000);
  };

  // Find max credits and calls to scale graphs
  const maxCredits = stats?.dailyStats && stats.dailyStats.length > 0
    ? Math.max(...stats.dailyStats.map(d => d.creditsUsed), 0.1)
    : 1;

  const maxCalls = stats?.dailyStats && stats.dailyStats.length > 0
    ? Math.max(...stats.dailyStats.map(d => d.callsCount), 1)
    : 1;

  if (!isAuthenticated) {
    return (
      <div className="relative min-h-screen flex items-center justify-center bg-[#07070a] overflow-hidden text-slate-100 px-4">
        {/* Glow Effects */}
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-600/15 rounded-full blur-[100px] pointer-events-none"></div>
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-blue-600/10 rounded-full blur-[120px] pointer-events-none"></div>

        <div className="w-full max-w-md backdrop-blur-xl bg-white/[0.03] border border-white/[0.08] p-8 rounded-2xl shadow-[0_8px_32px_0_rgba(0,0,0,0.37)]">
          <div className="text-center mb-8">
            <div className="inline-flex p-3 rounded-xl bg-white/[0.05] border border-white/10 mb-4 shadow-inner">
              <svg className="w-8 h-8 text-purple-400" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 01-1.043 3.296 3.745 3.745 0 01-3.296 1.043A3.745 3.745 0 0112 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 01-3.296-1.043 3.745 3.745 0 01-1.043-3.296A3.745 3.745 0 013 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 011.043-3.296 3.746 3.746 0 013.296-1.043A3.746 3.746 0 0112 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 013.296 1.043 3.746 3.746 0 011.043 3.296A3.745 3.745 0 0121 12z" />
              </svg>
            </div>
            <h1 className="text-2xl font-bold tracking-tight text-white">EchoFilter Admin</h1>
            <p className="text-sm text-slate-400 mt-2">Enter secret key to access dashboard metrics</p>
          </div>

          <form onSubmit={handleLogin} className="space-y-5">
            <div>
              <label htmlFor="secret" className="block text-xs font-semibold uppercase tracking-wider text-slate-300 mb-2">Admin Secret</label>
              <input
                id="secret"
                type="password"
                placeholder="Enter secret (default: admin123)"
                value={secretInput}
                onChange={(e) => setSecretInput(e.target.value)}
                className="w-full px-4 py-3 bg-white/[0.04] border border-white/10 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-500/50 focus:border-purple-500/50 transition-all placeholder:text-slate-500 text-white"
              />
            </div>

            {loginError && (
              <div className="p-3 bg-red-500/10 border border-red-500/20 text-red-300 text-xs rounded-lg flex items-center gap-2">
                <svg className="w-4 h-4 flex-shrink-0 text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                </svg>
                <span>{loginError}</span>
              </div>
            )}

            <button
              type="submit"
              className="relative w-full py-3 bg-gradient-to-r from-purple-600 to-blue-600 text-white font-semibold rounded-xl transition-all duration-300 hover:shadow-[0_0_20px_rgba(168,85,247,0.4)] hover:brightness-110 active:scale-[0.98] cursor-pointer flex items-center justify-center"
            >
              Sign In
            </button>
          </form>
        </div>
      </div>
    );
  }

  return (
    <div className="relative min-h-screen bg-[#07070c] text-slate-100 pb-12 font-sans antialiased">
      {/* Background glow meshes */}
      <div className="absolute top-0 right-1/4 w-[500px] h-[500px] bg-purple-600/10 rounded-full blur-[120px] pointer-events-none"></div>
      <div className="absolute bottom-10 left-10 w-[400px] h-[400px] bg-blue-600/5 rounded-full blur-[100px] pointer-events-none"></div>

      {/* Navigation Bar */}
      <nav className="sticky top-0 z-40 backdrop-blur-md bg-[#07070c]/70 border-b border-white/[0.06] py-4 px-6 md:px-12 flex justify-between items-center">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-lg bg-gradient-to-tr from-purple-600 to-blue-600 flex items-center justify-center shadow-lg shadow-purple-500/20">
            <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364-6.364l-.707.707M6.343 17.657l-.707.707m0-11.314l.707.707m11.314 11.314l.707-.707M12 5a7 7 0 100 14 7 7 0 000-14z" />
            </svg>
          </div>
          <div>
            <h1 className="font-bold tracking-tight text-white">EchoFilter <span className="text-xs bg-purple-500/10 border border-purple-500/20 text-purple-400 px-2 py-0.5 rounded-full font-normal ml-2">Admin Dashboard</span></h1>
          </div>
        </div>

        <div className="flex items-center gap-4">
          {stats && (
            <div className="hidden sm:flex items-center gap-2 px-3 py-1 rounded-full bg-white/[0.04] border border-white/5 text-xs text-slate-400">
              <span className={`w-2 h-2 rounded-full ${stats.groqKeyConfigured ? 'bg-emerald-500 shadow-[0_0_8px_#10b981]' : 'bg-rose-500 shadow-[0_0_8px_#f43f5e]'}`}></span>
              Groq API: {stats.groqKeyStatus}
            </div>
          )}
          <button
            onClick={handleLogout}
            className="px-3 py-1.5 text-xs bg-white/[0.05] border border-white/10 hover:bg-white/10 text-slate-300 rounded-lg transition-all active:scale-95 cursor-pointer"
          >
            Log Out
          </button>
        </div>
      </nav>

      {/* Main Container */}
      <main className="max-w-7xl mx-auto px-6 md:px-12 mt-8">
        
        {/* Error notification if database fetching failed */}
        {statsError && (
          <div className="mb-6 p-4 bg-red-500/10 border border-red-500/20 text-red-300 text-sm rounded-xl flex items-center justify-between">
            <div className="flex items-center gap-3">
              <svg className="w-5 h-5 text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
              </svg>
              <span>{statsError}</span>
            </div>
            <button onClick={fetchStats} className="px-3 py-1 bg-white/[0.06] border border-white/10 hover:bg-white/10 text-xs text-white rounded-lg transition-all">Retry</button>
          </div>
        )}

        {/* Supabase migration alert */}
        {stats && stats.tableExists === false && (
          <div className="mb-8 p-6 backdrop-blur-xl bg-amber-500/[0.03] border border-amber-500/20 text-amber-100 rounded-2xl shadow-lg">
            <div className="flex items-start gap-4">
              <div className="p-3 bg-amber-500/15 border border-amber-500/30 text-amber-400 rounded-xl">
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                </svg>
              </div>
              <div className="flex-1 space-y-3">
                <h3 className="text-lg font-bold text-white">Supabase Schema Migration Required</h3>
                <p className="text-sm text-slate-300">
                  The dashboard was loaded, but the <code className="px-1.5 py-0.5 rounded bg-white/[0.07] text-amber-300 font-mono text-xs">usage_logs</code> table was not detected in your Supabase database.
                  Please copy the SQL commands below, navigate to your <a href="https://supabase.com/" target="_blank" rel="noopener noreferrer" className="underline text-purple-400 hover:text-purple-300">Supabase SQL Editor</a>, run them, and then refresh this page.
                </p>
                <div className="relative mt-4 bg-[#0a0a0f] border border-white/10 rounded-xl p-4 font-mono text-xs text-slate-300 overflow-x-auto">
                  <pre>{sqlSchemaText}</pre>
                  <button
                    onClick={copySqlToClipboard}
                    className="absolute top-3 right-3 p-1.5 rounded-md bg-white/[0.05] border border-white/10 hover:bg-white/10 text-xs text-slate-300 flex items-center gap-1.5 transition-all cursor-pointer"
                  >
                    {copying ? (
                      <>
                        <svg className="w-3.5 h-3.5 text-emerald-400" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
                        <span className="text-emerald-400">Copied!</span>
                      </>
                    ) : (
                      <>
                        <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" /></svg>
                        <span>Copy SQL</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Dashboard Grid Content */}
        {loading ? (
          <div className="flex flex-col items-center justify-center py-20">
            <div className="w-12 h-12 rounded-full border-4 border-purple-500/20 border-t-purple-500 animate-spin mb-4"></div>
            <p className="text-sm text-slate-400">Loading telemetry data...</p>
          </div>
        ) : (
          stats && (
            <div className="space-y-8">
              
              {/* KPI Cards Row */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                
                {/* Card 1: Users */}
                <div className="backdrop-blur-md bg-white/[0.02] border border-white/[0.06] p-6 rounded-2xl relative overflow-hidden group">
                  <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-purple-500/0 via-purple-500/40 to-purple-500/0 opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                  <div className="flex justify-between items-start">
                    <div>
                      <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Total Users</p>
                      <h4 className="text-3xl font-extrabold text-white mt-2 tracking-tight">{stats.totalUsers}</h4>
                    </div>
                    <div className="p-2 rounded-xl bg-purple-500/10 border border-purple-500/20 text-purple-400">
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.109A11.386 11.386 0 0110.089 20c-1.602 0-3.136-.33-4.533-.924a9.005 9.005 0 01-1.247-.696 4.125 4.125 0 017.523-2.476A9.03 9.03 0 0015 19.128zm0 0c0-1.113-.285-2.16-.786-3.07M15 7.5a3 3 0 11-6 0 3 3 0 016 0zm6 2.25a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z" />
                      </svg>
                    </div>
                  </div>
                  <p className="text-xs text-slate-500 mt-4 flex items-center gap-1">
                    <span className="text-emerald-400 font-medium">Active</span> Chrome Extension users
                  </p>
                </div>

                {/* Card 2: Calls */}
                <div className="backdrop-blur-md bg-white/[0.02] border border-white/[0.06] p-6 rounded-2xl relative overflow-hidden group">
                  <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-blue-500/0 via-blue-500/40 to-blue-500/0 opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                  <div className="flex justify-between items-start">
                    <div>
                      <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Total Audits</p>
                      <h4 className="text-3xl font-extrabold text-white mt-2 tracking-tight">{stats.totalCalls}</h4>
                    </div>
                    <div className="p-2 rounded-xl bg-blue-500/10 border border-blue-500/20 text-blue-400">
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m3.75 9v6m3-3H9m1.5-12H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
                      </svg>
                    </div>
                  </div>
                  <p className="text-xs text-slate-500 mt-4 flex items-center gap-1">
                    YouTube videos analyzed in total
                  </p>
                </div>

                {/* Card 3: Credits Spent */}
                <div className="backdrop-blur-md bg-white/[0.02] border border-white/[0.06] p-6 rounded-2xl relative overflow-hidden group">
                  <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-pink-500/0 via-pink-500/40 to-pink-500/0 opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                  <div className="flex justify-between items-start">
                    <div>
                      <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Credits Consumed</p>
                      <h4 className="text-3xl font-extrabold text-white mt-2 tracking-tight">${stats.totalCreditsUsed.toFixed(2)}</h4>
                    </div>
                    <div className="p-2 rounded-xl bg-pink-500/10 border border-pink-500/20 text-pink-400">
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v12m-3-2.818l.214-.11a3.65 3.65 0 00.183-.37c.347-.836.347-1.765 0-2.602a3.673 3.673 0 00-.285-.542l-.112-.17a3.002 3.002 0 00-3.327-.584M21 18H3m14-9.3c0-2.6-2.1-4.7-4.7-4.7M10 3v4c0 1.1-.9 2-2 2H4" />
                      </svg>
                    </div>
                  </div>
                  <p className="text-xs text-slate-500 mt-4">
                    Based on standard rate of <span className="text-pink-400">$0.05</span>/analysis
                  </p>
                </div>

                {/* Card 4: Key status */}
                <div className="backdrop-blur-md bg-white/[0.02] border border-white/[0.06] p-6 rounded-2xl relative overflow-hidden group">
                  <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-emerald-500/0 via-emerald-500/40 to-emerald-500/0 opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                  <div className="flex justify-between items-start">
                    <div>
                      <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Server API Key</p>
                      <h4 className="text-3xl font-extrabold text-white mt-2 tracking-tight flex items-center gap-2">
                        {stats.groqKeyConfigured ? 'Active' : 'Missing'}
                      </h4>
                    </div>
                    <div className={`p-2 rounded-xl border ${stats.groqKeyConfigured ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400' : 'bg-rose-500/10 border-rose-500/20 text-rose-400'}`}>
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 5.25a3 3 0 013 3m3 0a6 6 0 01-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1121.75 8.25z" />
                      </svg>
                    </div>
                  </div>
                  <p className="text-xs text-slate-500 mt-4">
                    Used when client does not supply a key
                  </p>
                </div>
              </div>

              {/* Data Visualization and Administration Section */}
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                
                {/* Left side: Charts (2 cols span on large) */}
                <div className="lg:col-span-2 space-y-6">
                  
                  {/* Chart Card */}
                  <div className="backdrop-blur-md bg-white/[0.02] border border-white/[0.06] p-6 rounded-2xl">
                    <div className="flex justify-between items-center mb-6">
                      <div>
                        <h3 className="text-lg font-bold text-white">Daily Credit Consumption</h3>
                        <p className="text-xs text-slate-400">Total admin credits consumed per day</p>
                      </div>
                      <div className="flex gap-2">
                        <div className="flex items-center gap-1.5 text-xs text-slate-400">
                          <span className="w-2.5 h-2.5 rounded bg-purple-500"></span>
                          Credits Used
                        </div>
                        <div className="flex items-center gap-1.5 text-xs text-slate-400">
                          <span className="w-2.5 h-2.5 rounded bg-blue-500/30 border border-blue-500"></span>
                          API Calls
                        </div>
                      </div>
                    </div>

                    {/* SVG Bar Chart */}
                    <div className="w-full h-64 bg-black/20 border border-white/5 rounded-xl p-4 flex flex-col justify-end">
                      {stats.dailyStats && stats.dailyStats.length > 0 ? (
                        <div className="w-full h-full flex flex-col justify-between">
                          
                          {/* Graph Area */}
                          <div className="flex-1 flex items-end justify-around gap-2 px-4 border-b border-white/10 pb-2">
                            {stats.dailyStats.map((d, i) => {
                              const creditPct = (d.creditsUsed / maxCredits) * 100;
                              const callsPct = (d.callsCount / maxCalls) * 100;

                              return (
                                <div key={i} className="flex-1 flex flex-col items-center group relative h-full justify-end max-w-[50px]">
                                  {/* Tooltip */}
                                  <div className="absolute bottom-full mb-2 bg-slate-900 border border-white/10 text-[10px] text-white px-2 py-1 rounded shadow-lg pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap z-10 flex flex-col gap-0.5">
                                    <span className="font-bold text-slate-300">{d.date}</span>
                                    <span className="text-purple-400">Credits: ${d.creditsUsed.toFixed(2)}</span>
                                    <span className="text-blue-400">Calls: {d.callsCount}</span>
                                  </div>

                                  {/* Twin bars */}
                                  <div className="w-full flex items-end gap-1 h-full">
                                    {/* Calls Bar */}
                                    <div
                                      style={{ height: `${Math.max(callsPct, 5)}%` }}
                                      className="flex-1 bg-blue-500/20 border border-blue-500/40 rounded-t-sm transition-all duration-300 group-hover:brightness-125"
                                    ></div>
                                    {/* Credits Bar */}
                                    <div
                                      style={{ height: `${Math.max(creditPct, 5)}%` }}
                                      className="flex-1 bg-gradient-to-t from-purple-600 to-purple-400 rounded-t-sm transition-all duration-300 group-hover:brightness-125 group-hover:shadow-[0_0_8px_rgba(168,85,247,0.4)]"
                                    ></div>
                                  </div>
                                </div>
                              );
                            })}
                          </div>

                          {/* X-axis Labels */}
                          <div className="flex justify-around gap-2 px-4 pt-2 text-[9px] text-slate-500 font-mono">
                            {stats.dailyStats.map((d, i) => {
                              // Format date as MM/DD
                              const dateParts = d.date.split('-');
                              const label = dateParts.length > 2 ? `${dateParts[1]}/${dateParts[2]}` : d.date;
                              return (
                                <span key={i} className="flex-1 text-center truncate max-w-[50px]">
                                  {label}
                                </span>
                              );
                            })}
                          </div>
                        </div>
                      ) : (
                        <div className="w-full h-full flex flex-col items-center justify-center text-slate-500 text-xs">
                          <svg className="w-8 h-8 text-slate-600 mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                          </svg>
                          <span>No credits consumed yet. Once analysis runs, usage charts will display here.</span>
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Top Users Card */}
                  <div className="backdrop-blur-md bg-white/[0.02] border border-white/[0.06] p-6 rounded-2xl">
                    <h3 className="text-lg font-bold text-white mb-4">Top Extension Consumers</h3>
                    <div className="overflow-x-auto">
                      <table className="w-full text-left border-collapse text-sm text-slate-300">
                        <thead>
                          <tr className="border-b border-white/[0.06] text-xs font-semibold uppercase tracking-wider text-slate-400">
                            <th className="py-3 px-4">User ID (Identity)</th>
                            <th className="py-3 px-4 text-center">API Calls</th>
                            <th className="py-3 px-4 text-right">Estimated Credit Cost</th>
                          </tr>
                        </thead>
                        <tbody>
                          {stats.topUsers && stats.topUsers.length > 0 ? (
                            stats.topUsers.map((user, i) => (
                              <tr key={i} className="border-b border-white/[0.04] hover:bg-white/[0.02] transition-colors">
                                <td className="py-3.5 px-4 font-mono text-xs text-slate-200">{user.userId}</td>
                                <td className="py-3.5 px-4 text-center font-medium text-slate-100">{user.callsCount}</td>
                                <td className="py-3.5 px-4 text-right text-purple-400 font-semibold">${user.creditsUsed.toFixed(2)}</td>
                              </tr>
                            ))
                          ) : (
                            <tr>
                              <td colSpan={3} className="py-8 px-4 text-center text-slate-500 text-xs">
                                No consumer telemetry found. Run some extension scans to log database metrics.
                              </td>
                            </tr>
                          )}
                        </tbody>
                      </table>
                    </div>
                  </div>

                </div>

                {/* Right side: Key Configuration Form */}
                <div className="space-y-6">
                  
                  {/* Configuration Form Card */}
                  <div className="backdrop-blur-md bg-white/[0.02] border border-white/[0.06] p-6 rounded-2xl relative overflow-hidden">
                    <div className="absolute top-0 left-0 w-1.5 h-full bg-gradient-to-b from-purple-600 to-blue-600"></div>
                    
                    <h3 className="text-lg font-bold text-white flex items-center gap-2 mb-2">
                      <svg className="w-5 h-5 text-purple-400" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M10.343 3.94c.09-.542.56-.94 1.11-.94h1.093c.55 0 1.02.398 1.11.94l.149.894c.07.424.384.764.78.93.398.164.855.142 1.205-.108l.737-.527a1.125 1.125 0 011.45.12l.773.774c.39.39.43 1.016.12 1.45l-.526.737c-.25.35-.273.807-.11 1.204.165.397.505.71.93.78l.893.15c.543.09.94.559.94 1.109v1.094c0 .55-.397 1.02-.94 1.11l-.894.149c-.424.07-.764.383-.929.78-.165.398-.143.854.107 1.204l.527.738c.32.438.27 1.063-.12 1.451l-.774.773a1.125 1.125 0 01-1.449.12l-.738-.527c-.35-.25-.806-.272-1.203-.107-.398.165-.71.505-.781.929l-.149.894c-.09.542-.56.94-1.11.94h-1.094c-.55 0-1.019-.398-1.11-.94l-.148-.894c-.071-.424-.384-.764-.781-.93-.398-.164-.854-.142-1.204.108l-.738.527a1.125 1.125 0 01-1.45-.12l-.773-.774a1.125 1.125 0 01-.12-1.45l.527-.737c.25-.35.272-.806.108-1.204-.165-.397-.505-.71-.93-.78l-.894-.15c-.542-.09-.94-.56-.94-1.109v-1.094c0-.55.398-1.02.94-1.11l.894-.149c.424-.07.765-.383.93-.78.165-.398.143-.854-.108-1.204l-.526-.738a1.125 1.125 0 01.12-1.45l.773-.773a1.125 1.125 0 011.45-.12l.737.527c.35.25.807.272 1.204.108.397-.165.71-.505.78-.929l.15-.894z" />
                        <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                      </svg>
                      Server Credentials
                    </h3>
                    <p className="text-xs text-slate-400 mb-6">Update the master Groq API Key stored in `.env.local`</p>

                    <form onSubmit={handleUpdateConfig} className="space-y-4">
                      <div className="relative">
                        <label htmlFor="apiKey" className="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">Groq API Key</label>
                        <div className="relative">
                          <input
                            id="apiKey"
                            type={showGroqKey ? 'text' : 'password'}
                            placeholder="gsk_..."
                            value={groqKeyInput}
                            onChange={(e) => setGroqKeyInput(e.target.value)}
                            className="w-full pl-4 pr-10 py-3 bg-white/[0.03] border border-white/10 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-500/50 focus:border-purple-500/50 transition-all text-sm placeholder:text-slate-600 text-white font-mono"
                          />
                          <button
                            type="button"
                            onClick={() => setShowGroqKey(!showGroqKey)}
                            className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-white transition-colors cursor-pointer"
                          >
                            {showGroqKey ? (
                              <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M3.98 8.223A10.477 10.477 0 001.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.45 10.45 0 0112 4.5c4.756 0 8.773 3.162 10.065 7.498a10.523 10.523 0 01-4.293 5.774M6.228 6.228L3 3m3.228 3.228l3.65 3.65m7.815 7.815L21 21m-3.228-3.228l-3.65-3.65m0 0a3 3 0 10-4.243-4.243m4.242 4.242L9.88 9.88" />
                              </svg>
                            ) : (
                              <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.43 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                                <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                              </svg>
                            )}
                          </button>
                        </div>
                      </div>

                      {configSuccess && (
                        <div className="p-3 bg-emerald-500/10 border border-emerald-500/20 text-emerald-300 text-xs rounded-lg flex items-center gap-2">
                          <svg className="w-4 h-4 flex-shrink-0 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                          <span>{configSuccess}</span>
                        </div>
                      )}

                      {configError && (
                        <div className="p-3 bg-red-500/10 border border-red-500/20 text-red-300 text-xs rounded-lg flex items-center gap-2">
                          <svg className="w-4 h-4 flex-shrink-0 text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                          <span>{configError}</span>
                        </div>
                      )}

                      <button
                        type="submit"
                        disabled={configLoading}
                        className="w-full py-2.5 bg-gradient-to-r from-purple-600 to-blue-600 hover:brightness-110 active:scale-[0.98] disabled:opacity-50 disabled:scale-100 text-white font-semibold text-sm rounded-xl transition-all duration-300 cursor-pointer shadow-[0_0_10px_rgba(147,51,234,0.2)] hover:shadow-[0_0_15px_rgba(147,51,234,0.4)] flex items-center justify-center gap-2"
                      >
                        {configLoading ? (
                          <>
                            <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin"></div>
                            <span>Saving key...</span>
                          </>
                        ) : (
                          <span>Update API Key</span>
                        )}
                      </button>
                    </form>
                  </div>

                  {/* Security Advisory Card */}
                  <div className="backdrop-blur-md bg-white/[0.01] border border-white/[0.04] p-5 rounded-2xl text-xs text-slate-400 space-y-2.5">
                    <h4 className="font-bold text-slate-300 flex items-center gap-1.5 uppercase tracking-wide">
                      <svg className="w-4 h-4 text-pink-400" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.57-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" />
                      </svg>
                      Security Notice
                    </h4>
                    <p>
                      Updating the server Groq Key directly modifies your local environment. This is immediately propagated to the API endpoints.
                    </p>
                    <p>
                      To change the login secret key, modify the <code className="px-1 py-0.5 rounded bg-white/[0.05] font-mono text-[10px] text-pink-300">ADMIN_SECRET</code> variable inside the <code className="font-mono text-slate-300">.env.local</code> configuration on disk.
                    </p>
                  </div>

                </div>

              </div>

            </div>
          )
        )}

      </main>
    </div>
  );
}
